### ISSUE TITLE
Resize reference maps

### ISSUE THREAD

**Issue by kuybeda** [KryoEM/relion2#10]
Resize reference maps
·         Relion does not support initial model building ab initio; therefore at least once during processing, an outside map must be brought in
·         We want to add a feature to automatically re-scale the imported map to the right pixel size, and re-size it to the correct box size
o    Currently, this has to be done outside the pipeline, with IMOD or with the Relion command line tool relion_image_handler
·         Best place to do this is probably to wrap the 3D classification and auto-refine modules with a command to re-size the reference map first
o    These are the only two modules that could require a reference map
o    These two modules also require input particles, and their metadata .star file will include information about their pixel size

**Comment by kuybeda** [comment]
@darthweider Are you sure we also need to resize the box to match the particle box size in addition to rescaling the pixel size? Does relion_image_handler do both?

**Comment by darthweider** [comment]
Yes, Relion will complain and not run if you give it a reference that is not the same box size.

relion_imagine_handler can do rescaling pixel size and resizing box size.

If, say, we have a .mrc map of a reference at 1Å/px, and we want to rescale it to 0.425Å/px and a box size of 256 x 256 x 256, we can do something like:
```
relion_image_handler --i 5A1A.mrc --angpix 1 --rescale_angpix 0.425 --o 5A1A_scaled.mrc
relion_imagine_handler --i 5A1A_scale.mrc --new_box 256 --o 5A1A_scaled_boxed.mrc
```

I can write a Python script for this, which will determine output pixel size and box size from the input particles, and then pass it onto @a-re to integrate into the GUI and core code.


Another functionality we can add is to also accept pdb files and convert those to .mrc (will first need to check how easy it is to implement)

**Comment by darthweider** [comment]
Another functionality we can add is to also accept pdb files and convert those to .mrc for the user.

This will require the pdb2mrc module found in EMAN, which we will have to also install onto the machines. 

Alternatively, we can just add instructions to the help tooltip saying "if you have a pdb, you have to concert to mrc first using Chimera or EMAN"

**Comment by darthweider** [comment]
Written and debugged; will run a quick test on the gpu machines next week to make sure it works before pushing to repo

**Comment by darthweider** [comment]
Pushed to repo relion2/python/Star/mrc_autosize.py


Run with command such as: 
`python mrc_autosize.py --i 5a1a_4A.mrc --o 5a1a_4A_bin3.mrc --ref ../../data/betagal_unittest/shiny_particles.star 
`

Will print output such as:

```
Input map 5a1a_4A.mrc
Pixel size 1.333A/px
Box size 154 x 121 x 87

Basing calculations on first particle stack found in reference star file.
Reference stack /shared/data/betagal_unittest/Particles/BetaGal_20141212_0004.mrcs
Pixel size 0.957000A/px
Box size 420^3

Creating a copy of the input map.

Resizing the map to a cube.
   0/   0 sec ............................................................~~(,_,">

Rescaling map to pixel size of 0.957000A/px
   2/   2 sec ............................................................~~(,_,">

Resizing map to box size of 420 x 420 x 420
   1/   1 sec ............................................................~~(,_,">


Auto-sizing completed. New map located at: 5a1a_4A_bin3.mrc
```
