### ISSUE TITLE
Automatic creation of output directories for unblur_tbz

### ISSUE THREAD

**Issue by darthweider** [KryoEM/relion2#11]
Before running Unblur, the script should create any output directories that do not already exist.

e.g.
unblur_tbz --output ./Unblur/Movies/
should create the folders ./Unblur/ and ./Unblur/Movies if they do not already exist

**Comment by kuybeda** [comment]
@dartweider This should also work with the latest version. Could you please very that?

**Comment by darthweider** [comment]
Will do -- I'm probably going to debug the sanity check tomorrow and can easily verify from that.
