### ISSUE TITLE
Integrate mrc_autosize into Relion GUI

### ISSUE THREAD

**Issue by darthweider** [KryoEM/relion2#14]
Currently, Relion class3d and refine3d require reference maps (i.e. initial models) that must be exactly the same magnification and box size as the input particles.

mrc_autosize.py is a script that automatically rescales + resizes an input map, of any magnification or box size, to the dimensions of a given .star list of particles.

The script has already been written (described in #10 ), and is located in repo relion2/python/Star/mrc_autosize.py, but needs to be integrated into Relion GUI -- either as a separate step in the GUI or behind-the-curtains as part of class3d and refine3d.

Do not do this until after installation of Relion 2.0.3 stable release.

**Comment by kuybeda** [comment]
We need to revisit this task, as Relion 2.0.4 has been merged with already

**Comment by darthweider** [comment]
it just occurred to me that we will have to figure out what to do with the "is reference map on absolute grayscale?" option for 3d classification and refinement.

If the map has been resized, this should be set to "no" and Relion should do it automatically.

One option is to always set this to "no" -- supposedly, asking Relion to do it even if it doesn't need to be done will not hurt.

**Comment by darthweider** [comment]
Checked -- grayscale does not seem to be changed when autosizing.
