### ISSUE TITLE
mpirun hosts file support

### ISSUE THREAD

**Issue by kuybeda** [KryoEM/relion2#19]

**Comment by darthweider** [comment]
Added to playbook: create sample host file in {{ relion_install_dir }}mpirun_default.hosts
Host file lists all machines included in the playbook, and assigns 1 slot to each of them.

The GUI can reference this file as a default hosts file.

**Comment by a-re** [comment]
I added hostfile support and round robin scheduling support in the latest commits: all I had to do was add the `--bynode` parameter to mpirun for round robin and `--hostfile <hostfile>` for the hostfile support.

**Comment by kuybeda** [comment]
I close this issue, but there is another one that needs to get finished, which relates to having a default hosts file created and specified in the relion gui.
