### ISSUE TITLE
Change UnblurTBZ GUI command

### ISSUE THREAD

**Issue by darthweider** [KryoEM/relion2#20]
Replace GUI command for UnblurTBZ.

 
Currently, it is:
````
for file in /etc/profile.d; do . $file; done; `which unblur_tbz.py` -i tbz.star  …
 ````
 
Replace with command:
````
bash -l -c "`which unblur_tbz.py` -i tbz.star  … "
````
(note the quotes)

**Comment by arestifo** [comment]
I added this change in the latest commits, but I haven't had the opportunity to thoroughly test it. I will be finished with all testing by our meeting on wednesday 3/8/2017

**Comment by kuybeda** [comment]
I tested it works
