### ISSUE TITLE
Link 'relion_unblur_tbz_mpi' to unblur_tbz.py executable

### ISSUE THREAD

**Issue by darthweider** [KryoEM/relion2#24]
Relion GUI checks for prefix `relion_` and suffix `_mpi` in order to run something through mpirun. Therefore, `unblur_tbz.py` currently cannot be run from the GUI (though there is currently a quick fix in place by removing this check).

Create a link named `relion_unblur_tbz_mpi` which points to `unblur_tbz.py`; tell Relion GUI to use that link.

* `ln -s relion2/python/unblur_tbz.py relion_unblur_tbz_mpi` Push to relion2 repo
* Change GUI command to run `which relion_unblur_tbz_mpi`
* Test to make sure changes work
* Remove quick fix commit

**Comment by kuybeda** [comment]
I think that the name should still have .py at the end. It still should
work.

**Comment by darthweider** [comment]
@kuybeda  Do you know what exactly the check searches for? "relion_" and "_mpi" anywhere in the command? You said Relion looks for the executable, but the executable in this case is technically bash.

Currently the command is:
````
bash -l -c "`which unblur_tbz.py` -i ./Import/job001/movies.star -o UnblurTBZ/job020/ -f 3 -l 20 -un /shared/apps/Unblur/unblur_1.0.2/bin/unblur_openmp_7_17_15.exe -sm /shared/apps/Summovie/summovie_1.0.2/bin/sum_movie_openmp_7_17_15.exe"
````

I was going to change it to:
````
bash -l -c "`which relion_unblur_tbz_mpi` -i ./Import/job001/movies.star -o UnblurTBZ/job020/ -f 3 -l 20 -un /shared/apps/Unblur/unblur_1.0.2/bin/unblur_openmp_7_17_15.exe -sm /shared/apps/Summovie/summovie_1.0.2/bin/sum_movie_openmp_7_17_15.exe"
````

and have this `relion_unblur_tbz_mpi` just be a symlink to unblur_tbz.py

**Comment by kuybeda** [comment]
rolled back checking for relion_ and _mpi substrings and renamed the python script. It should work as long as the command string has those substrings in it.
