### ISSUE TITLE
Sync with Relion 2.04

### ISSUE THREAD

**Issue by kuybeda** [KryoEM/relion2#27]
Use git to merge our Relion fork with the official relion version and document this procedure in a wiki.

**Comment by kuybeda** [comment]
What is the status of this task? 

We need to think whether we are ready to merge the development branch back into master.

**Comment by a-re** [comment]
Just merged 2.0.4 into branch `tbzmotion`. Also wrote a guide in this repo's wiki of how to merge new version of RELION when they come out.
