### ISSUE TITLE
Troubleshoot unblur to polishing step

### ISSUE THREAD

**Issue by darthweider** [KryoEM/relion2#38]

**Comment by darthweider** [comment]
@kuybeda  Two changes need to be made to UnblurTBZ:

1) Averaged micrographs should not have a suffix. Use `mic001.mrc`, not `mic001_movie_avg.mrc` 
2) Movie files should be in .mrcs format, not .mrc. Change `mic001_movie_aligned.mrc` to `mic001_movie_aligned.mrcs`

Also,
3) During Movie Refinement step, the default GUI field for the movie file suffix should be changed from `movie` to `movie_aligned` since that is what you changed it to for UnblurTBZ.

**Comment by darthweider** [comment]
Also, note that after these changes are implemented, projects that used the old naming system will toss out errors about not finding files. There's not much that can be done about it -- you'll just have to rename things manually to the correct naming system.

**Comment by kuybeda** [comment]
Thanks!
