### ISSUE TITLE
Default hostfile support in GUI

### ISSUE THREAD

**Issue by darthweider** [KryoEM/relion2#41]
GUI hostfile field should:
1) point to the default hostfile (whether it is located in an environment variable specified path or `.default_hostfile` in the project directory)

2) be saved as the job setting the next time the GUI is opened up. This will probably be done through the hidden files such as `.gui_autopick` or `.gui_autorefine`

**Comment by arestifo** [comment]
Done in commit #8cb67c8 in tbzmotion-2.0.6 branch
