### ISSUE TITLE
Unblur_tbz support for .mrc files

### ISSUE THREAD

**Issue by kuybeda** [KryoEM/relion2#8]
Some automated data collection software (e.g. at the ATC) end up depositing frames as gain-corrected .mrc files, such as: mic001_frame01.mrc, mic001_frame02.mrc …
·         Example: any tbz from /data/Livlab/projects_d3414/Csy/
·          Add support for these in unblur_tbz
·         After untarring, run command to package frames into single file: newstack mic001_*.mrc mic001.mrcs
·         Then proceed immediately to unblur

**Comment by kuybeda** [comment]
@darthweider How do you know that those mrc files are already gain corrected? What is pixel precision there? Is it also 8 bits/pixel?

**Comment by darthweider** [comment]
I have a dataset collected by Prashant via automated collection at the ATC which are tarred .mrc files, and he told me that the images are gain-corrected. 

Those files I have from him are 32-bit float (what IMOD calls mode 2). 

Perhaps the more elegant way to do this is to read the pixel precision from the header of the .mrc file using the IMOD module:
header -mode input.mrc
This way, we don't have to rely on the pixel precision as an invariant.
(List of supported IMOD modes: http://bio3d.colorado.edu/imod/doc/mrc_format.txt) 


We can also make the gain correction file an optional input, and only apply gain correction if the file is provided as input. Another option (if we are worried about user error) is to do what Alberto does in Spy -- look in the tbz folders and then pull out gain correction files.

**Comment by kuybeda** [comment]
I would prefer to avoid getting entangled into over-complicated schemes. The right way of storing electron counting data is 8 bit period. It may be dm4, or mrc (per data collection software), but they both have to be 8 bit per pixel mode. Any other format is invalid and shall not be used, as it would take 4 fold more storage. 

In this view, I do see that your /data/Livlab/projects_d3414/Csy/ data is stored in mrc format with 8 bit mode. If these files are gain-corrected, then it must be 16-factor rounding scheme. 

As the folder also contains K2-0001 1 Gain Ref. x1.m3.dm4 gain reference, I'm still not sure whether those mrc files have been corrected or not.

**Comment by kuybeda** [comment]
Meanwhile implemented decompression of mrc files followed by gain correction. Since dm4 has x and y coordinates, opposite to those in mrc, the gains file is transposed prior to applying it to mrc stack.

**Comment by darthweider** [comment]
I'll take a look again and check with Prashant re: gain correction.

**Comment by darthweider** [comment]
Ok I checked with Prashant and figured out the confusion:

The first folder
data/Livlab/projects_d3414/Csy/Csy_Acrf10_20161221/ 
was collected manually at the ATC. Therefore, it is not gain-corrected and is at 8-bit pixel resolution. Also, for some reason, these are dimensions 7420 x 7676.

All other folders
data/Livlab/projects_d3414/Csy/Csy_Acrf10_20170105/ 
data/Livlab/projects_d3414/Csy/Csy_Acrf10_20170118/ 
data/Livlab/projects_d3414/Csy/Csy_dsDNA_20170110/ 
were collected automatically by software at the ATC. These **are** gain-corrected **and** at 32-bit pixel resolution. (Both Prashant and Sriram know that this is happening) They are dimensions 7676 x 7420. 


Given that the ATC microscope is still being set up, the variety of micrograph formats might just be a kink that will be worked out once the microscope is fully operational and automated. Therefore, I propose that we ignore .mrc format micrographs for now (or only offer very basic support), and check back in later to see what formatting the ATC has settled on.

**Comment by darthweider** [comment]
(The issue I raised in the email about Unblur outputting in 32-bit is unrelated to this -- it's just by coincidence that I found that issue while checking out this one)

**Comment by kuybeda** [comment]
Totally agree about getting back to mrc when the format gets finalized.
Meanwhile, there is code that is easy to adapt to whatever final format is.
I hope that ATC settles on 8bit/pixel for the storage and data transfer
reasons.

**Comment by darthweider** [comment]
@kuybeda Just wanted to check -- do you transpose the .dm4 gain reference file when the micrographs are also .dm4?

I suspect that maybe micrographs are generally consistent with the gain reference file (requiring no transposition), and it might just be this particular dataset that is odd.
